### ISSUE TITLE
dalton_controller constantly restarting.

### ISSUE THREAD

**Issue by datmanslo** [secureworks/dalton#130]
**Cause**:
```
Traceback (most recent call last):
  File "/opt/dalton/run.py", line 2, in <module>
    from flask_cache import Cache
  File "/usr/local/lib/python2.7/site-packages/flask_cache/__init__.py", line 24, in <module>
    from werkzeug import import_string
ImportError: cannot import name import_string
```

**Workaround**:
Add `werkzeug==0.16.1` to requirements.txt

**Comment by counterthreatunit** [comment]
Thanks! Fixed in https://github.com/secureworks/dalton/pull/131.
